ibm:
  - zopendebug: 5.4.0
  - zopeneditor: 5.5.0
  - zcommoncomponent: 16.1.25061109
  - zfilemanager: 16.1.25061109
  - zfaultanalyzer: 16.1.25061109
  - db2forzosdeveloperextension: 2.2.2
  - ibm-developer: 1.0.1
  - wca-core: 1.6.2

galasa:
  - galasa-plugin: 0.13.0

vscjava:
  - vscode-maven: 0.44.2024072906

broadcommfd:
  - explorer-for-endevor: 1.11.1
  - abend-analyzer: 1.3.0
  - ccf: 1.2.1
  - data-editor-for-mainframe: 1.0.0
  - debugger-for-mainframe: 1.13.0
  - hlasm-language-support: 1.17.0
  - cobol-language-support: 2.4.0
  - jcl-language-support: 3.0.0
  - lsp-for-rexx: 0.0.18

zowe:
  - cics-extension-for-zowe: 3.8.0
  - zowe-explorer-ftp-extension: 3.2.1
  - vscode-extension-for-zowe: 3.2.1

redhat:
  - vscode-yaml: 1.18.0
  - ansible: 25.4.0

ms-vscode-remote:
  - remote-wsl: 0.99.0
  - remote-ssh: 0.120.0
  - remote-containers: 0.422.0

ms-vscode:
  - remote-server: 1.5.2

ms-ceintl:
  - vscode-language-pack-zh-hant: 1.101.2025061109