vscode:
  dir: vscode
  type: "zip"
  pattern: "VSCode*"
  source: https://code.visualstudio.com/sha/download?version=1.101.0&os=win32-x64-archive
  add_home_path_to_env: false
python:
  dir: python
  type: "zip"
  pattern: "*python*"
  source: https://github.com/winpython/winpython/releases/download/15.3.20250425final/Winpython64-3.13.3.0dot.zip
  add_home_path_to_env: true
  home_path_of:
    - "python.exe"
nodejs:
  dir: node
  type: "zip"
  pattern: "*node*"
  source: https://nodejs.org/dist/v22.16.0/node-v22.16.0-win-x64.zip
  add_home_path_to_env: true
  home_path_of:
    - "node.exe"
groovy:
  dir: groovy
  type: "zip"
  pattern: "*groovy*"
  source: https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-sdk-4.0.27.zip
  add_home_path_to_env: true
  home_path_of:
    - "groovy.bat"
git:
  dir: git
  type: "7z.exe"
  pattern: "PortableGit*"
  source: https://github.com/git-for-windows/git/releases/download/v2.50.0.windows.1/PortableGit-2.50.0-64-bit.7z.exe
  add_home_path_to_env: true
  home_path_of:
    - "git.exe"
maven:
  dir: mvn
  type: "zip"
  pattern: "*maven*"
  source: https://dlcdn.apache.org/maven/maven-3/3.9.10/binaries/apache-maven-3.9.10-bin.zip
  add_home_path_to_env: true
  home_path_of:
    - "mvn.cmd"
zowe-core:
  dir: zowe-cli/core
  type: "zip"
  pattern: "zowe*package*"
  source: https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/3.2.0/zowe-cli-package-3.2.0.zip
  add_home_path_to_env: false
zowe-plugin:
  dir: zowe-cli/plugins
  type: "zip"
  pattern: "zowe*plugins*"
  source: https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/3.2.0/zowe-cli-plugins-3.2.0.zip
  add_home_path_to_env: false
java21:
  dir: java/21
  type: "zip"
  pattern: "*jdk*21*"
  source: https://github.com/ibmruntimes/semeru21-binaries/releases/download/jdk-21.0.7%2B6_openj9-0.51.0/ibm-semeru-open-jdk_x64_windows_21.0.7_6_openj9-0.51.0.zip
  add_home_path_to_env: true
  home_path_of: 
    - "java.exe"