release:
  name: "VSCode4z"
  version: "2.5.0"
  description: "VSCode4z is a tool for installing VSCode and extensions for Zowe"
  author: "IBM Taiwan Expert Labs"
  license: "MIT"
  homepage: "https://github.com/nicholas-yahung-chien/ibm-vscode-4-z"
  repository: "https://github.com/nicholas-yahung-chien/ibm-vscode-4-z"
  keywords: ["vscode", "zowe", "zopeneditor", "wca4z", "watsonx"]
  exclude_dirs: [".git"]
  exclude_files: ["*.tmp"]